# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/civil',
                'doc_host': 'https://civildot.github.io',
                'git_url': 'https://github.com/civildot/civil',
                'lib_path': 'civil'},
  'syms': {'civil.core': {'civil.core.foo': ('core.html#foo', 'civil/core.py')}}}
